### PR TITLE
Typos, nits through page 94

### PR DESCRIPTION
**Pull request by rsjordan**
Typos, nits through page 94

### CODE REVIEW

**Comment by vladak** [comment]
Looks like spell-check failed with `adirectory` - seems like a missing space.

**Comment by vladak** [comment]
Pls leave this open, just add another commit with the spelling fixup.

**Comment by vladak** [comment]
Merging, thanks !

**Comment by rsjordan** [comment]
I was trying to remove the Czech lines from file-api.tex.  Do I still need
to do that?

**Comment by vladak** [comment]
I filed issue for that, don't worry about thiat for now.

Dne po 4. 6. 2018 8:11 uživatel Ron Jordan <notifications@github.com>
napsal:

**Pull request merged**
