### PR TITLE
rsjordan - some minor typos and changes to intro.tex 

### PR DESCRIPTION
**Pull request by rsjordan**
Some minor typos and changes for intro.tex (up to "API vs ABI").

### CODE REVIEW

**Comment by rsjordan** [comment]
Not sure why there are two commits.  My 1st attempt at making  a pull request turned out to be for my own branch.  After merging that pull request into my branch, I created a pull request for the devnull-cz/unix-linux-prog-in-c repository.  Changes in the changesets for each commit seem to be the same.

**Comment by rsjordan** [comment]
The Travis CI build chokes on line 848.   Not sure what was changed on line 848, but any change to this line was unintentional.  Same for the changes at 859, 935, 1185, and 1814.  All of my changes to intro.tex were done via the web browser interface.

**Comment by vladak** [comment]
line 848 contains untranslated term. I will just merge this and deal with it afterwards.

**Comment by vladak** [comment]
merged the 1st commit by hand. The failure was due to encoding change in the untranslated term.

Thanks and keep it coming !

**Pull request closed without merging**
